/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { EmoticonSummaryResponse } from './emoticonSummaryResponse';

/**
 * 댓글 정보
 */
export interface CommentResponse {
  /** 댓글 ID */
  id?: number;
  /** 작성자 ID */
  userId?: number;
  /** 작성자 이름 */
  userName?: string;
  /** 작성자 프로필 이미지 URL */
  userProfileImageUrl?: string;
  /** 댓글 내용 (삭제된 댓글은 고정 문구로 대체됨) */
  content?: string;
  /** 작성일 */
  commentedAt?: string;
  /** 이모지 목록 */
  emoticons?: EmoticonSummaryResponse[];
  /** 답글 목록 (1-depth, 답글에는 답글이 없음) */
  replies?: unknown;
  isEditable?: boolean;
  isEdited?: boolean;
}
