/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 알림 종류
 */
export type NotificationResponseType =
  (typeof NotificationResponseType)[keyof typeof NotificationResponseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationResponseType = {
  COMMENT: 'COMMENT',
  REACTION: 'REACTION',
  UPLOAD: 'UPLOAD',
} as const;
