/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationResponseType } from './notificationResponseType';

/**
 * 알림함 항목
 */
export interface NotificationResponse {
  /** 알림 식별자(UUID). 읽음 처리 API 의 경로 변수이자 FCM data payload 의 notifId 와 같은 값 */
  notifId: string;
  /** 알림 종류 */
  type: NotificationResponseType;
  /** 알림 제목 */
  title: string;
  /** 알림 본문. 그룹 윈도우가 아직 열려 있으면 첫 이벤트 시점 문구다(최대 5분). */
  body: string;
  /** 묶인 이벤트 개수. 마감 전에는 body 와 개수가 어긋날 수 있다. */
  groupCount: number;
  /** 발송 시각 */
  sentAt: string;
  /** 딥링크 대상 사진 id */
  targetPhotoId: number;
  /** 딥링크 힌트 주소. null 이면 prod 응답에서 필드 자체가 생략된다(non_null). */
  targetAddress?: string;
  isRead?: boolean;
}
