/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 알림 종류별 스위치. 서버가 아는 모든 종류의 값을 항상 명시적으로 내려준다. 저장된 적 없는 종류는 true 다. null 을 절대 포함하지 않는다(prod non_null 직렬화와 무관하게).
 */
export type NotificationSettingsResponseTypes = { [key: string]: boolean };
