/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationResponse } from './notificationResponse';

export interface PageResultNotificationResponse {
  content?: NotificationResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
  isLast?: boolean;
}
