/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterDeviceTokenRequestPlatform } from './registerDeviceTokenRequestPlatform';

/**
 * 디바이스 토큰 등록 요청
 */
export interface RegisterDeviceTokenRequest {
  /**
   * FCM 등록 토큰
   * @minLength 0
   * @maxLength 512
   */
  token: string;
  /** 디바이스 플랫폼 */
  platform: RegisterDeviceTokenRequestPlatform;
}
