/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 디바이스 플랫폼
 */
export type RegisterDeviceTokenRequestPlatform =
  (typeof RegisterDeviceTokenRequestPlatform)[keyof typeof RegisterDeviceTokenRequestPlatform];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDeviceTokenRequestPlatform = {
  ANDROID: 'ANDROID',
  IOS: 'IOS',
  WEB: 'WEB',
} as const;
