/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 안읽은 알림 존재 여부
 */
export interface UnreadExistsResponse {
  /** 안읽은 알림이 하나라도 있는지 여부 */
  hasUnread: boolean;
}
