/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 변경할 종류만 담는다. 여기 없는 종류는 변경되지 않는다. 생략 시 변경 없음.
 */
export type UpdateNotificationSettingsRequestTypes = { [key: string]: boolean };
