/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateNotificationSettingsRequestTypes } from './updateNotificationSettingsRequestTypes';

/**
 * 알림 설정 부분 변경 요청. 생략한 필드는 변경하지 않는다.
 */
export interface UpdateNotificationSettingsRequest {
  /** 전체 알림 마스터 스위치. 생략 시 변경 없음. */
  masterEnabled?: boolean;
  /** 변경할 종류만 담는다. 여기 없는 종류는 변경되지 않는다. 생략 시 변경 없음. */
  types?: UpdateNotificationSettingsRequestTypes;
}
