/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Lokit API
 * Lokit API 문서
 * OpenAPI spec version: 1.0.0
 */

/**
 * 댓글 수정 요청
 */
export interface UpdateCommentRequest {
  /**
   * 댓글 내용
   * @minLength 0
   * @maxLength 500
   */
  content: string;
}
